<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>address</name>
   <tag></tag>
   <elementGuidId>305058f7-7399-4fc2-ba7f-2742f2e235cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[6]/div[3]/div/div[1]/div/div[2]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[6]/div[3]/div/div[1]/div/div[2]/ul/li[2]/a</value>
   </webElementProperties>
</WebElementEntity>
