<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>computer</name>
   <tag></tag>
   <elementGuidId>b67e89c1-ad72-4ed8-a3a9-b32729b5b668</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[6]/div[2]/ul[1]/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[6]/div[2]/ul[1]/li[1]/a</value>
   </webElementProperties>
</WebElementEntity>
