<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wishlist</name>
   <tag></tag>
   <elementGuidId>7b784a85-4ca6-4df6-aa04-acb3023e534f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[6]/div[1]/div[1]/div[2]/div[1]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[6]/div[1]/div[1]/div[2]/div[1]/ul/li[3]/a</value>
   </webElementProperties>
</WebElementEntity>
